val-town/val-town-docs

- src/content/docs/rest-api/express.md
> Fix express note

- src/content/docs/examples/jsx.md
- src/content/docs/examples/lodash.md
- src/content/docs/examples/push-notifications.md
- src/content/docs/examples/save-html-form-data.md
- src/content/docs/examples/web-scraping.md
- src/content/docs/info/contact-us.md
- Add jsx pragma example code
- Link to discord from info page
- Fix email link on info page
> Copyediting pass

- astro.config.mjs
> enable editLink option

- src/content/docs/api/run.mdx
- src/content/docs/contact-us/contact-us.md
Also adds another meta description.
> Link to email signup

- public/_headers
> Add long-lived caching headers to resources

- src/content/docs/std/SQLite/index.mdx
- src/content/docs/std/SQLite/usage.mdx
- src/content/docs/std/blob.mdx
- src/content/docs/std/email.md
- src/content/docs/std/fetch.md
> Add links to std vals in Standard Library section

- src/content/docs/reference/custom-domains.md
This page explains custom domains, how to set them up, and also has the DNS configuration instructions.
> Write custom domains docs page

- src/content/docs/reference/custom-domains.md
- add badge to the sidebar item
- add an annotation on top of the page that links to the pricing page
Closes #86
> Mark the custom domains feature as a Pro feature

- src/content/docs/guides/interop.md
> Document interoperability with runtimes

- src/content/docs/std/email.md
Based on [val.town/v/std/email](https://www.val.town/v/std/email)
> Add `replyTo` in email docs

- package-lock.json
- package.json
Bumps all direct and indirect dependencies.
> Monthly dep bumps

- src/content/docs/api/esm-town.mdx
- src/content/docs/guides/embed.mdx
- src/content/docs/guides/generate-pdfs.mdx
- src/content/docs/guides/rss.mdx
- src/content/docs/guides/web-scraping.mdx
- src/content/docs/integrations/airtable.mdx
- src/content/docs/reference/custom-domains.md
- src/content/docs/reference/environment-variables.md
- src/content/docs/reference/import.mdx
- src/content/docs/reference/permissions.mdx
- src/content/docs/reference/runtime.mdx
- src/content/docs/reference/shortcuts.mdx
- src/content/docs/reference/version-control.mdx
- src/content/docs/std/SQLite/index.mdx
- src/content/docs/std/SQLite/migrations.mdx
- src/content/docs/std/SQLite/orms.mdx
- src/content/docs/std/SQLite/usage.mdx
- src/content/docs/std/blob.mdx
- src/content/docs/std/email.md
- src/content/docs/std/fetch.md
- src/content/docs/troubleshooting/empty-object.md
- src/content/docs/troubleshooting/exports.md
- src/content/docs/types/email.mdx
- src/content/docs/types/http/basic-examples.mdx
- src/content/docs/types/http/jsx.mdx
- src/content/docs/types/http/routing.mdx
- src/content/docs/types/scheduled.mdx
- src/content/docs/types/script.md
- src/styles/custom.css
Made a bunch of edits: just read the docs, from top to bottom (and got a little tired of reading by the time I got to integrations, so those are lightly edited if at all).
> Documentation cleanup and editing pass

- src/content/docs/std/SQLite/index.mdx
> Add LibSQL Studio

- src/content/docs/quickstarts/first-cron.mdx
Small typo :) perfect timing on these docs, just signed up yesterday.
> Fix typo in first-cron.mdx

- src/content/docs/api/overview.mdx
Follow-up to launching code-powered documentation.
> Update OpenAPI link to point to new docs

- src/content/docs/guides/creating-a-webhook.mdx
Just found a little typo. Really enjoying playing around with Val Town!
> Fix typo in creating-a-webhook.mdx

- src/content/docs/reference/townie.mdx
This is a first draft of a reference doc for Townie. Let me know if this follows our style and if there's anything else we should add
[Preview](https://github.com/val-town/val-town-docs/blob/townie-reference/src/content/docs/reference/townie.mdx)
> Add townie reference doc

- src/content/docs/index.mdx
> "recommend" typo

- src/content/docs/troubleshooting/cors.md
for: https://github.com/val-town/val.town/pull/6385
> Add CORS docs page

- src/content/docs/index.mdx
> The Townie link is broken

- src/content/docs/index.mdx
> Fix small typo in docs index.mdx

- src/content/docs/vals/http/custom-domains.md
The custom domain docs are helpful, thanks! I got mine working quickly (Cloudflare apex domain).
> Fix typos in custom-domains.md

- astro.config.mjs
> Fixed first website link

- src/content/docs/reference/deno-lsp.mdx
Sorry I made these changes and forgot to push them :/
> Fix the 'is' typo

- src/content/docs/reference/version-control.mdx
Context: https://discord.com/channels/1020432421243592714/1401752158977916980/1401752158977916980
> Clarify unpinned import version control

- astro.config.mjs
- src/content/docs/api/index.mdx
- src/content/docs/api/sdk.mdx
- src/content/docs/guides/in-val-out.mdx
- src/content/docs/guides/rss.mdx
- src/content/docs/guides/save-html-form-data.mdx
- src/content/docs/guides/web-scraping.mdx
- src/content/docs/index.mdx
- src/content/docs/legacy-vals/express.mdx
- src/content/docs/legacy-vals/index.mdx
- src/content/docs/quickstarts/first-website.mdx
- src/content/docs/quickstarts/prompting.mdx
- src/content/docs/reference/esm-town.mdx
- src/content/docs/reference/import.mdx
- src/content/docs/reference/permissions.mdx
- src/content/docs/std/SQLite/index.mdx
- src/content/docs/std/email.md
- src/content/docs/vals/branches.mdx
- src/content/docs/vals/email.mdx
- src/content/docs/vals/http/index.mdx
- src/content/docs/vals/index.mdx
- src/content/docs/vals/pull-requests.mdx
- src/content/docs/vals/remixes.mdx
1. Adds guide for I/V/O pattern
2. Updates home page to improve information hierarchy
3. Fixes broken links, fix [starlight-links-validator](https://starlight-links-validator.vercel.app/getting-started/) config, convert relative links to absolute (to enable validation)
4. Updates instructions for PRs
> In, Val, Out (aka user alerts)
