src/content/docs/std/SQLite/usage.mdx
Fixed a typo (`cosnsole.log`) in the SQLite usage docs
=> Fixed typo in SQLite usage example

astro.config.mjs, package-lock.json, package.json, plugins/val-town-open-button.mjs, src/content/docs/types/http/jsx.mdx, src/content/docs/types/scheduled.mdx
Hopefully solves #26
This PR introduces ability to mark code blocks so that they will display a "Open in Val Town" button. When the button is pressed it opens a new tab with the code ready in Val Town (`https://www.val.town/embed/new?code=...`).
You can see examples in `scheduled.mdx` and `jsx.mdx`.
A code block must:
- be one of the supported languages: `js`/`jsx`/`ts`/`tsx`
- have the `val` meta tag added to it
Examples of such code blocks:
````md
```ts val
// Code block without a title
```
```js val
// example.js
// Code block with a title
```
```tsx title="Example" {2-3} val
// Has title
// and
// Has code highlighting
```
````
If the code block has a title, it will display a large button in the top bar. Currently there is no icon next to the big button as I'm not sure what the …
=> Implement "Open In Val Town" button for selected code blocks

package-lock.json, package.json
There's a useful new feature in the links validator - https://github.com/HiDeoo/starlight-links-validator/issues/21
Relative links aren't validated so they're often silently wrong. This will raise an error on a detected relative link.
=> Update links-validator so that we catch relative links

src/content/docs/types/http/jsx.mdx
Added an example of Hono's [JSX support](https://hono.dev/guides/jsx) to the http/jsx section.
I opted for using the NPM package with a `jsxImportSource` directive instead of their suggested Deno import, in order to keep a similar style to the other examples.
=> Add hono JSX example

src/content/docs/std/fetch.md
* clarify "standard fetch" vs std/fetch
The documentation for `std/fetch` uses the words "standard fetch", even though it's actually not referring to `std/fetch`. Someone new to Javascript may find this confusing and have difficulty following the docs. So, I wanted to make the distinction very clear in the wording.
* emphasize and punch-up the value provided by the out-of-the-box proxy functionality
=> Rewrite std/fetch overview

src/content/docs/std/SQLite/orms.mdx
That `:::` looks strange on the page https://docs.val.town/std/sqlite/orms/
I'm pretty sure that this is just a bug. That `:::` was the closing for `:::note[Sequelize]`, but after commit https://github.com/val-town/val-town-docs/commit/469511e7ab883a9337e7343d59a743922ad011d9 there is no more `:::note[Sequelize]` (it was in file `src/content/docs/std/sqlite.mdx`, github by default does not expand diff for that file)
=> Removed markup remnants

src/content/docs/api/aliases.mdx, src/content/docs/api/my-resources.mdx, src/content/docs/api/run.mdx, src/content/docs/api/users.mdx, src/content/docs/api/vals.mdx
I've updated the API documentation in the following way:
- Added descriptions from the [OpenAPI Spec](https://www.val.town/docs/openapi.yaml) to each endpoint in the docs
- Updated the example for `POST /v1/vals` to reflect that it is possible to include readme and privacy in the request body
- Added the `PUT /v1/vals` endpoint and added an example for it
- Added the `GET /v1/me/references` endpoint and example for it
- Changed `handle` where it was used in the API docs to better reflect what the path parameter is (it was used for both val_name and username)
- 
Partially resolves #100
=> Update to API docs

src/content/docs/troubleshooting/permission-errors.md
Realized that we didn't have documentation for this, and it'd be useful to - this doc pages talks about Deno's limited sandbox and the common workaround of using esm.sh.
=> Write documentation for troubleshooting permissions

src/content/docs/types/http/routing.mdx
- Demonstrate setting up [feTS server](https://the-guild.dev/openapi/fets/server/quick-start)
- Demonstrate using the [feTS client](https://the-guild.dev/openapi/fets/client/quick-start) with types imported from the server val
=> Add feTS to HTTP routing documentation

src/content/docs/contact-us/security.md
This adds a list of in-scope domains and a list of explicit out-of-scope issues to our security policy.
=> Expand on security policy and explicit exclusions

src/content/docs/types/http/basic-examples.mdx, src/content/docs/types/http/early-return.mdx, src/content/docs/types/http/index.mdx, src/content/docs/types/http/jsx.mdx, src/content/docs/types/http/routing.mdx
Adds a new section to the HTTP val type docs about early-returning HTTP responses.
=> Async docs draft

src/content/docs/std/SQLite/usage.mdx
Closes #131 
Previous links were redirecting to a generic "Introduction" page of Turso docs.
=> Update outdated Turso docs links

astro.config.mjs
Noticed that our docs page titles don't include "Val Town" and I suspect that they would have better SEO & recognizability if they did.
=> Add Val Town to titles

plugins/val-town-open-button.mjs
This is a workaround for Cloudflare's WAF, which we can't turn off yet, which prevents the "Run In Val Town" button from working. This base64-encodes payloads to the `/new` page in Remix.
=> Support base64-encoded new code

plugins/val-town-open-button.mjs
I think this is mildly suspect because a meta with `ts title="title with lowercase val in it"` will match, but this should work for now.
=> Fix run in val town link regression

src/content/docs/reference/custom-domains.md
Val Town uses [SaaS Custom Domains](https://saascustomdomains.com) to power custom domains.
=> Add 'Powered by [SaaS Custom Domains](https://saascustomdomains.com)' footer to custom-domains docs.

plugins/val-town-open-button.mjs, src/content/docs/guides/creating-a-webhook.mdx, src/content/docs/guides/generate-pdfs.mdx, src/content/docs/guides/rss.mdx, src/content/docs/guides/save-html-form-data.mdx, src/content/docs/integrations/Discord/how-to-make-a-discord-bot-hosted-24-7-for-free-in-.mdx, src/content/docs/integrations/Discord/send-message.mdx, src/content/docs/integrations/GitHub/receiving-a-github-webhook.mdx, src/content/docs/integrations/Slack/bot.mdx, src/content/docs/integrations/telegram.mdx, src/content/docs/types/email.mdx, src/content/docs/types/http/early-return.mdx, src/content/docs/types/http/index.mdx, src/content/docs/types/http/jsx.mdx, src/content/docs/types/http/routing.mdx, src/content/docs/types/script.md
The changes are here:
- https://replace-http-code-block-exam.val-town-docs.pages.dev/guides/creating-a-webhook/
- https://replace-http-code-block-exam.val-town-docs.pages.dev/guides/generate-pdfs/
- https://replace-http-code-block-exam.val-town-docs.pages.dev/guides/save-html-form-data/
- https://replace-http-code-block-exam.val-town-docs.pages.dev/integrations/discord/how-to-make-a-discord-bot-hosted-24-7-for-free-in-/
- https://replace-http-code-block-exam.val-town-docs.pages.dev/integrations/discord/send-message/
- https://replace-http-code-block-exam.val-town-docs.pages.dev/integrations/github/receiving-a-github-webhook/
- https://replace-http-code-block-exam.val-town-docs.pages.dev/integrations/slack/bot/
- https://replace-http-code-block-exam.val-town-docs.pages.dev/integrations/tele …
=> Replace some code blocks intended to be HTTP vals with embed equivalents

_redirects, astro.config.mjs, src/content/docs/guides/rss.mdx, src/content/docs/guides/save-html-form-data.mdx, src/content/docs/index.mdx, src/content/docs/integrations/GitHub/receiving-a-github-webhook.mdx, src/content/docs/quickstarts/first-cron.mdx, src/content/docs/reference/environment-variables.mdx, src/content/docs/troubleshooting/exports.md, src/content/docs/types/cron.mdx, src/content/docs/types/email.mdx, src/content/docs/types/http/early-return.mdx, src/content/docs/types/script.md, src/content/docs/upgrading/upgrade-to-deno.md
Mostly renaming "interval" to "cron" and dropping the word "handler" from val types.
One URL change: /types/scheduled to /types/cron, for which I added a redirect.
=> Consistent naming of val types VAL-19716

public/openapi.html, public/openapi.json
Adds an OpenAPI docs page at `/openapi`. This will theoretically replace https://api.val.town/documentation - and come with the benefit of integrated code examples.
=> Add openapi docs

src/content/docs/integrations/s3.mdx
Existing endpoint triggers a
``The server unexpectedly returned a redirect response. With AWS S3, this usually means you need to use a ` +
`region-specific endpoint like "s3.us-west-2.amazonaws.com" instead of "s3.amazonaws.com"``
=> add region to s3 endpoint

src/content/docs/troubleshooting/express-to-http-migration.md
This doc will be linked to from the email / blog post about the plan to deprecate Express vals.
=> Documentation for the http to express migration

src/content/docs/reference/custom-domains.md
- Use fully qualified domain names (`example.com.` with a `.` at the end) in custom domain examples
- Add a note about CNAME flattening
=> Clarify Custom Domains page

src/content/docs/reference/bot-rate-limiting.mdx
The new page: https://bot-limits.val-town-docs.pages.dev/reference/bot-rate-limiting/
=> Add bot limits

src/content/docs/integrations/sqlite-wasm.mdx
The docs show two ways to do SQLite-in-val: [SQLite wasm](https://docs.val.town/integrations/sqlite-wasm/), and [`std/sqlite`](https://docs.val.town/std/sqlite/), which is much more performant.
I'd propose deprecating the older solution.
=> Deprecate SQLite wasm in favor of new `std/sqlite`

src/content/docs/integrations/sqlite-wasm.mdx
Oops! I had the wrong casing for the SQLite WASM deprecation link in #248.
=> Fix SQLite WASM deprecation URL

src/content/docs/reference/environment-variables.mdx
This page is linked in the global environment variables page. 
Adding a line about Project environment variables for clarity.
=> Added Projects to Environment Variables docs

src/content/docs/guides/interop.md, src/content/docs/reference/permissions.mdx
Updates the permissions documentation to denote the new privacy behavior and adds a section describing the legacy private state.
=> Rework privacy docs to cover new private behavior

src/content/docs/api/authentication.mdx, src/content/docs/api/sdk.mdx
- Updated SDK starter, it's currently broken after recent SDK changes.
- Added clarity around how to access your default injected Val Town API token
(Thanks to @dcm31 for flagging that these are out of date) :)
=> Updated SDK starter and default API token injection
